apiVersion: v1
kind: Service
metadata:
  name: corp-banking-api-active
  labels:
    app: corp-banking-api
spec:
  selector:
    app: corp-banking-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: corp-banking-api-preview
  labels:
    app: corp-banking-api
spec:
  selector:
    app: corp-banking-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
