apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  selector:
    app: fraud-detection
  ports:
  - name: http
    port: 80
    targetPort: 8093
  type: ClusterIP
