apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: corporate-banking

bases:
  - ../../base

replicas:
  - name: corp-banking-api
    count: 1

patches:
  - target:
      kind: Deployment
      name: corp-banking-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENVIRONMENT
            value: "dev"
  - target:
      kind: ConfigMap
      name: corp-banking-api-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "dev"
