apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loans-prod-na

bases:
  - ../../base

resources:
  - rollout.yaml

patches:
  - target:
      kind: ConfigMap
      name: loans-ui-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "prod-na"

