apiVersion: v1
kind: Service
metadata:
  name: document-processing-active
  labels:
    app: document-processing
spec:
  selector:
    app: document-processing
  ports:
  - name: http
    port: 80
    targetPort: 8084
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: document-processing-preview
  labels:
    app: document-processing
spec:
  selector:
    app: document-processing
  ports:
  - name: http
    port: 80
    targetPort: 8084
  type: ClusterIP
