apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-banking

bases:
  - ../../base

commonLabels:
  environment: preprod

replicas:
  - name: retail-banking-api
    count: 3

patches:
  - target:
      kind: Deployment
      name: retail-banking-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENVIRONMENT
            value: "preprod"
  - target:
      kind: ConfigMap
      name: retail-banking-api-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "preprod"
