apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: corporate-banking-dev

bases:
  - ../../base

replicas:
  - name: treasury-service
    count: 1

patches:
  - target:
      kind: Deployment
      name: treasury-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENVIRONMENT
            value: "dev"
  - target:
      kind: ConfigMap
      name: treasury-service-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "dev"
