apiVersion: v1
kind: Service
metadata:
  name: credit-scoring
  labels:
    app: credit-scoring
spec:
  selector:
    app: credit-scoring
  ports:
  - name: http
    port: 80
    targetPort: 8085
  type: ClusterIP
