apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: corporate-banking

bases:
  - ../../base

resources:
  - rollout.yaml

patches:
  - target:
      kind: ConfigMap
      name: treasury-service-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "prod-eu"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause: { duration: 10m }
        - setWeight: 25
        - pause: { duration: 10m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 100

