apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loans

resources:
  - ../../base
  - rollout.yaml

patches:
  - target:
      kind: ConfigMap
      name: loans-api-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "prod-na"

