apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: corporate-banking

bases:
  - ../../base

resources:
  - rollout.yaml

patches:
  - target:
      kind: ConfigMap
      name: corp-banking-api-config
    patch: |-
      - op: add
        path: /data/ENVIRONMENT
        value: "prod-apac"

