apiVersion: v1
kind: Service
metadata:
  name: logging-service-active
  labels:
    app: logging-service
spec:
  selector:
    app: logging-service
  ports:
  - name: http
    port: 80
    targetPort: 8094
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service-preview
  labels:
    app: logging-service
spec:
  selector:
    app: logging-service
  ports:
  - name: http
    port: 80
    targetPort: 8094
  type: ClusterIP
