apiVersion: v1
kind: Service
metadata:
  name: treasury-service
  labels:
    app: treasury-service
spec:
  selector:
    app: treasury-service
  ports:
  - name: http
    port: 80
    targetPort: 8081
  type: ClusterIP
