apiVersion: v1
kind: Service
metadata:
  name: retail-banking-api
  labels:
    app: retail-banking-api
spec:
  selector:
    app: retail-banking-api
  ports:
  - name: http
    port: 80
    targetPort: 8090
  type: ClusterIP
