apiVersion: v1
kind: Service
metadata:
  name: loans-api
  labels:
    app: loans-api
spec:
  selector:
    app: loans-api
  ports:
  - name: http
    port: 80
    targetPort: 8083
  - name: metrics
    port: 9090
    targetPort: 8083
  type: ClusterIP
